#设置多环境配置
spring:
  profiles:
        active: dev  #加载application-dev.properties文件
  application:
    name: eureka-client-example1 #设置服务实例名称 名称不可用下划线分割
#配置端口号
server:
  port: 9001


eureka:
  instance:
    prefer-ip-address: true #是否显示IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
          defaultZone: http://localhost:9000/eureka/ #配置注册中心地址
