spring:
  application:
    name: hystrix-turbine #指定应用名称 名称不可用下划线分割
#指定服务端口
server:
  port: 9005
eureka:
    instance:
      prefer-ip-address: true #是否显示IP地址
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
      service-url:
        defaultZone: http://localhost:9000/eureka/ #配置注册中心地址

turbine:
  #要监控的微服务列表，多个用，隔开
  appConfig: eureka-client-example1,feign-client-example3
  clusterNameExpression: "'default'"