spring:
  application:
    name: zuul-server #指定应用名称 名称不可用下划线分割
#指定服务端口
server:
  port: 8081
#基础路由配置
zuul:
  routes:
    #client-serviceId: #路由id 随便写,但必须唯一
    # path: /client-example1/**    #映射路径
      #url: http://127.0.0.1:9001/ #映射路径对应的微服务
      #serviceId: eureka-client-example1 #配置转发的微服务名称
     #如果路由id与servcieId一致 可简化如下路由配置
     eureka-client-example1: /client-example1/**    #映射路径

#配置注册中心
eureka:
  instance:
    prefer-ip-address: true #是否显示IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ #配置注册中心地址
#设置hystrix超时时间为5000ms,之后才调用降级方法，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
ribbon:
  ReadTimeout: 5000 #负载均衡超时时间，默认值5000
  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000