#配置端口号
server:
  port: 10001
#设置多环境配置
spring:
  application:
    name: config-server #设置服务实例名称 名称不可用下划线分割
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/gaoming1/config-repositry.git
  #配置消息中间件
  rabbitmq:
    username: guest
    password: guest
    port: 5672
    host: 127.0.0.1
#开启动态刷新的请求路径端点
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
eureka:
  instance:
    prefer-ip-address: true #是否显示IP地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ #配置注册中心地址

